### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by vitaly-t**
Are you having trouble with pg-promise? ;)

### CODE REVIEW

**Comment by SCdF** [comment]
Nope, I'm trying to work out why Travis doesn't like certain postgres commands I'm using. It fails for them in either your library or pg. It looks like it's because they are on 9.4.0 (or I'm picking my postgres version wrong), and the command I want is fixed in a later 9.4.x version.

**Comment by vitaly-t** [comment]
You can have Travis use PostgreSQL 9.5, they provide instructions on how to do that ;)

**Comment by SCdF** [comment]
I understand that, but test environments should mimic production environments, and the production environment I will be working with is 9.4.x

**Comment by vitaly-t** [comment]
Anyway, pg-promise itself should work without issues. If you have any - let us know ;)

**Pull request closed without merging**
